#!/bin/bash

# Quick Setup Script for Cloudflare Turnstile Integration
# Run this after getting your credentials from Cloudflare

echo "🔐 Cloudflare Turnstile Setup Helper"
echo "===================================="
echo ""
echo "Step 1: Get your credentials from Cloudflare"
echo "  → Go to https://dash.cloudflare.com/"
echo "  → Select your domain (or add turuturustars.co.ke)"
echo "  → Security → Turnstile → Create Site"
echo "  → Copy your Site Key (public key)"
echo ""
echo "Step 2: Create .env.local file"
echo "  → Create file: .env.local"
echo "  → Add: VITE_CLOUDFLARE_SITE_KEY=your_site_key_here"
echo ""
echo "Step 3: Configure Supabase Dashboard"
echo "  → Go to https://app.supabase.com/"
echo "  → Select project: mkcgkfzltohxagqvsbqk"
echo "  → Settings → Auth → Captcha"
echo "  → Enable Captcha"
echo "  → Select Provider: Turnstile"
echo "  → Paste your Secret Key (from Cloudflare, NOT the site key)"
echo "  → Save"
echo ""
echo "Step 4: Push Supabase Config"
echo "  → Run: supabase push"
echo ""
echo "Step 5: Test"
echo "  → npm run dev"
echo "  → Go to http://localhost:5173/auth"
echo "  → Switch to Sign In tab"
echo "  → Complete the captcha"
echo "  → Try logging in"
echo ""
echo "✅ Setup complete!"
